# Generated by Django 3.1.4 on 2020-12-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'FS',
                'verbose_name_plural': 'FS',
            },
        ),
        migrations.AlterModelOptions(
            name='fn',
            options={'verbose_name': 'FN', 'verbose_name_plural': 'FN'},
        ),
        migrations.AlterModelOptions(
            name='fv',
            options={'verbose_name': 'FV', 'verbose_name_plural': 'FV'},
        ),
        migrations.AlterModelOptions(
            name='gt',
            options={'verbose_name': 'Gt', 'verbose_name_plural': 'Gt'},
        ),
        migrations.AlterModelOptions(
            name='k',
            options={'verbose_name': 'K', 'verbose_name_plural': 'K'},
        ),
        migrations.AlterModelOptions(
            name='ket',
            options={'verbose_name': 'Ket', 'verbose_name_plural': 'Ket'},
        ),
        migrations.AlterModelOptions(
            name='o',
            options={'verbose_name': 'O', 'verbose_name_plural': 'O'},
        ),
        migrations.AlterModelOptions(
            name='p',
            options={'verbose_name': 'P', 'verbose_name_plural': 'P'},
        ),
        migrations.AlterModelOptions(
            name='pel',
            options={'verbose_name': 'Pel', 'verbose_name_plural': 'Pel'},
        ),
        migrations.AlterModelOptions(
            name='pn',
            options={'verbose_name': 'Pn', 'verbose_name_plural': 'Pn'},
        ),
        migrations.AlterModelOptions(
            name='ps',
            options={'verbose_name': 'Ps', 'verbose_name_plural': 'Ps'},
        ),
        migrations.AlterModelOptions(
            name='s',
            options={'verbose_name': 'S', 'verbose_name_plural': 'S'},
        ),
    ]
