from ..models import *
cnf = {
    'K': ['S P', 'K O', 'K Pel', 'K Ket'],
    'S': ['FN Gt', 'FN FN', 'FN Pn', 'Ps FN', 'FN Ps', 'Pn FN', 'Ia', 'Dane', 'Titiang', 'Batur', 'Astawa', 'Pemedek', 'Wisatawan', 'Bali', 'Pembeli'],
    'P': ['FV Ps', 'Ps FN', 'Ps FV', 'FV FN', 'FV FV', 'Ps FS', 'Pn FS', 'FV FS', 'Pn FV', 'mamula', 'meliang', 'ngadepang', 'medagang', 'medue', 'nyihnayang', 'nangiang', 'naptiang', 'nedungin', 'negesan', 'ngaptiang', 'ngamargiang', 'katureksain', 'nyarengin', 'ngaryanin', 'ngemastikayang', 'kalaksanayang', 'kaloktah', 'nuturang', 'pilot', 'bapan', 'ngadep', 'ngelaksanayang', 'nangiang', 'maweweh', 'negesan'],
    'O': ['FN FS', 'Ps FS', 'FN FN', 'Pn FN', 'FN Pn', 'FN Ps', 'adine', 'memene', 'jaja', 'kaluwihan', 'kramane', 'Bencana', 'jukut', 'swadharma', 'UMKM', 'padi'],
    'Pel': ['FN FN', 'FV FN', 'Pn FN', 'Ps FV', 'Ps FN', 'PHK', 'jukut', 'buku'],
    'Ket': ['Ps FN', 'Pn FN', 'FN Pn', 'FV FN', 'Pr FS'],
    'FN': ['FN FN', 'FN Pn', 'Pn FN', 'FN FV', 'FN Kt', 'Pr FN', 'FN Ps', 'Ps FN', 'berdaulat', 'sejarah', 'bangsa', 'Indonesia', 'strategis', 'tunggil', 'I', 'Bapa', 'uma', 'ituni', 'semengan', 'toko', 'Gramedia', 'peken', 'Klungkung', 'jiwa', 'seni', 'kentel', 'kramane', 'Industri', 'pariwisata', 'kauratiang', 'UMKM', 'Bali', 'UMKM', 'perekonomian', 'iraga', 'mecikang', 'angga', 'Satuan', 'pendidikan', 'sistem', 'presida', 'mewali', 'dumun', 'Yayasan', '16', 'satuan', 'pendidikan', 'kerjasama', 'Dewa', 'Indra', 'kramane', 'masang', 'Bendera', 'Merah', 'Putih', 'Dewa', 'Indra', 'krama', 'Bali', 'makasami', 'tenaga', 'Penyuluh', 'Bahasa', 'Bali', 'Desa', 'Beraban', 'alit-alit', 'para', 'yowana', 'desa', 'Baraban', 'Pemerintah', 'Desa', 'Beraban', 'parikrama', 'Bulan', 'Bahasa', 'Bali', 'warsa', '2020', 'akeh', 'basa', 'campuran', 'Dina', 'mabasa', 'geguat', 'ngranjing', 'pura', 'Akeh', 'sumeken', 'acara', 'Para', 'yowana', 'Galungan', 'Ibu', 'jero', '15', 'porsi', 'abon', 'pindang', 'Utsaha', 'kuliner', 'jeronnyane', 'Akeh', 'pamikarya', 'Gubernur', 'Bali', 'parindikane', 'Menteri', 'Pariwisata', 'ekonomi', 'Makehan', 'perajin', 'karya', 'malakar', 'kayu', 'Istri', 'Gubernur', 'Bali', 'Wayan', 'Koster', 'angga', 'Pasar', 'Gotong', 'Royong', 'Pangan', 'Krama', 'Bali', 'hari', 'kerja', 'Putri', 'Koster', 'parikrama', 'HATINYA', 'PKK', 'Gubernur', 'Koster', 'suksmaning', 'manah', 'fraksi-fraksi', 'DPRD', 'Provinsi', 'Bali', 'Aksi', 'terorisme', 'dura', 'Negara', 'kawentenan', 'budayane', 'Para', 'yowana', 'seseleh', 'becik', 'karesikan', 'kasucian', 'palemahan', 'pura', 'Dosen', 'Bahasa', 'Lan', 'Sastra', 'Bali', 'Unud', 'acara', 'Ngewacen', 'Cerpen', 'I', 'Gede', 'Putra', 'Ariawan', 'Industri', 'pariwisata', 'lantang', 'pemargi', 'Gubernur', 'Koster', 'parikrama', 'konferensi', 'kabencana', 'Bali', 'Benjang', 'Gunung', 'pulah', 'palih', 'nyanggra', 'kabencana', 'Krama', 'Pasien', '11', 'rumah', 'sakit', 'Gubernur', 'Wayan', 'Koster', 'kauratiang', 'Desa', 'Adat', 'pidartane', 'Makasami', 'pasien', 'Covid-19', '15', 'diri', 'Respati', 'Kawentenang', 'PBMB', 'kramane', 'masan', 'pandemi', 'Guru', 'Besar', 'ISI', 'Denpasar', 'pemilet', 'utsaha', 'baga', 'usaha', 'bengkel', 'majeng', 'krama', 'sami', 'Ps FN', 'baga', 'kalih', 'Kadek', 'Suprapta', 'Meranggi', 'pengalgal', 'acara', 'titi', 'majeng', 'rare', 'angon', 'Wakil', 'Gubernur', 'Bali', 'Tjokorda', 'Oka', 'Artha', 'Ardhana', 'Sukawati', 'pacentokan', 'layangan', 'virtual', 'sesuduk', 'becik', 'dane', 'genah', 'PMI', 'pulah', 'palih', 'bapan', 'Luh', 'sari', 'Anak', 'lanang', 'Sekretaris', 'Daerah', 'Provinsi', 'Bali', 'Kalih', 'diri', 'negatif', 'Covid-19'],
    'FV': ['Ps FV', 'FV FV', 'nyujur', 'nguripan', 'mapinunas', 'mapangapti', 'nganggen', 'majanten', 'prasida', 'kalaksanayang', 'makarya', 'maosang', 'keni', 'mawesana', 'nangian', 'nincapan', 'ngaturang', 'katangarin', 'kaaptiang', 'ngicen', 'nyarengin', 'nyaga', 'nyumbungan', 'mapikayun', 'nindihin', 'ngambil', 'nyanggra', 'ngerauhan', 'katambanin', 'kantos', 'kaucap', 'ngelaksanayang', 'kauningin', 'mekarya', 'nyarengin', 'mungkah', 'dados', 'raris', 'nyontoang', 'memargi'],
    'FS': ['FS FS', 'Ps FS', 'gering', 'nenten', 'uning', 'kenak', 'urati', 'sumeken', 'satia', 'embas', 'Tetujone'],
    'Gt': ['tiange'],
    'Pn': ['majeng', 'ring', 'Sane', 'wantah', 'antuk', 'sareng', 'ka', 'majeng', 'pungkur', 'punika', 'ring', 'sane', 'puniki', 'para', 'olih', 'indik'],
    'Ps': ['di', 'sinalih', 'inggih', 'sane', 'mageng', 'ring', 'tetep', 'masan', 'setata', 'mangda', 'ajah-ajah', 'sekadi', 'mangda', 'dahat', 'becik', 'pisan', 'kantos', 'taler', 'tan', 'surud-surud', 'patut', 'setata', 'sangkaning', 'naler', 'mangda', 'banget', 'kaaptiyang', 'dahat', 'indik', 'taler', 'patut', 'durung', 'becik', 'indik', 'pastika', 'makasami', 'mangda', 'lan', 'positif', 'pinaka', 'sampun', 'Para', 'kantun'],
    'Pr': ['wiadin', 'sane', 'miwah'],
    'Kt': ['pungkuran'],
}
